#!/bin/bash

#     Created by Louis Teboul (a.k.a Androguide.fr) 
#     admin@androguide.fr
#     http://androguide.fr // http://pimpmyrom.org
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

CYAN="\\033[1;36m"
RED="\\033[1;31m"
GREEN="\\033[1;32m"
RESET="\\e[0m"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo -e "${CYAN}Downloading the Android SDK & Android Studio...${RESET}"
wget http://dl.google.com/android/studio/android-studio-bundle-130.737825-linux.tgz
mv android-studio-bundle-130.737825-linux.tgz adt-bundle.tgz
tar -zxvf adt-bundle.tgz
mv adt-bundle/android-studio/{,.}* adt-bundle/
rm -rf adt-bundle/android-studio

echo -e "${CYAN}Downloading gradle v1.7...${RESET}"
wget http://services.gradle.org/distributions/gradle-1.7-bin.zip
mv gradle-1.7-bin.zip gradle.zip
unzip gradle.zip

echo -e "${CYAN}Setting-up environment variables for the SDK...${RESET}"
export PATH=$PATH:$DIR/adt-bundle/sdk/tools
export PATH=$PATH:$DIR/adt-bundle/sdk/platform-tools
export PATH=$PATH:$DIR/adt-bundle/sdk/build-tools
echo "export PATH=$PATH:$DIR/adt-bundle/sdk/tools" >> ~/.bashrc
echo "export PATH=$PATH:$DIR/adt-bundle/sdk/platform-tools" >> ~/.bashrc
echo "export PATH=$PATH:$DIR/adt-bundle/sdk/build-tools" >> ~/.bashrc

echo -e "${CYAN}Setting-up environment variables for Android Studio...${RESET}"
export PATH=$PATH:$DIR/adt-bundle/bin
echo "export PATH=$PATH:$DIR/adt-bundle/bin" >> ~/.bashrc

echo -e "${CYAN}Setting-up environment variables for gradle...${RESET}"
export PATH=$PATH:$DIR/gradle/bin
echo "# Android Development Tools" >> ~/.bashrc
echo "export PATH=$PATH:$DIR/gradle/bin" >> ~/.bashrc

echo -e "${GREEN}DONE! Your Android Development Tools are now setup!${RESET}"